// <auto-generated />
namespace BankTr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddFrignKeyStateToTrans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFrignKeyStateToTrans));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181258050_AddFrignKeyStateToTrans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
